### ISSUE TITLE
Console is printing white by default

### ISSUE THREAD

**Issue by TheBrenny** [roblatour/setvol#1]
https://github.com/roblatour/setvol/blob/main/setvol/Module1.vb#L808 sets the colour to be white by default. This looks odd in consoles where the background colour is white.

I suggest that the default value of the param is null and set the colour to what is passed, or `Console.ResetColor()`.

Ty for the great app though! 🎉🎉 I can finally persist volume balance! 😅

**Comment by roblatour** [comment]
Hi Jarod,

I made a change to correct the issue you reported.

[cid:6e1aa629-3fc0-4dad-b6f3-fcc043917d43]

You can download the beta executable from here:
https://6ec1f0a2f74d4d0c2019-591364a760543a57f40bab2c37672676.ssl.cf5.rackcdn.com/SetVolbeta.zip

Please let me know if this addresses your issue, and if yes I will post the revision.

Best Regards,

Rob


________________________________

**Comment by roblatour** [comment]
Ok, just to let you know, I've applied this change and updated the source on github and the executable that you can download from https://www.rlatour.com/setvol/index.html

SetVol - free command line utility to set your Windows master volume level - rlatour.com<https://www.rlatour.com/setvol/index.html>
Setup:. SetVol does not need to be installed, rather just unzip it from the download file (above) and run it. S ource:. SetVol 's source code can be found here.. Using SetVol:. From the command prompt just type "setvol ?"
www.rlatour.com
Thanks again for reporting the issue.

Rob

________________________________
