### ISSUE TITLE
Feature Request:  New switch to report if audio currently playing on the system

### ISSUE THREAD

**Issue by cssyphus** [roblatour/setvol#2]
Hi Rob, thanks for this useful util.

Any poss to add a new switch that would report back (boolean) if audio is currently playing on the system?

Windows has the "Volume Mixer" (C:\Windows\System32\SndVol.exe, or RClick on volume icon in systray) that displays a real-time volume meter... could setvol tap into that (or other Windows service) to report back whether audio is currently playing on the system?

**Comment by roblatour** [comment]
You're very welcome.

Yes, I think that would be possible.

Can you please email me at info@rlatour.com to discuss further?

**Comment by roblatour** [comment]
functionality added in version 3.0 - released December 12, 2021.
