### ISSUE TITLE
Feature Request: timeout

### ISSUE THREAD

**Issue by cssyphus** [roblatour/setvol#3]
Hi Rob,

Thanks again for the latest updates. After using SetVol3 for a couple of days, and while it's still fresh in your mind, I have an observation.  

The absolute min timeout before reporting "no sound" is 1 sec, which is long enough to be noticeable to the user but is a very long time to the computer. _(Also, there seems - on my i7/32Gb/SSD system at least - to be an in-built delay of ~ 1sec starting the program under Win10, and then the 1sec sampling delay on top of that does make it noticeable)._ 

I wonder if you would consider allowing the minimum allowable test time to be smaller - would tenths of a sec (e.g. 0.1sec/0.5secs be unreasonable? Would 0.5secs be the lowest you would go? Or would there be no point allowing a test time smaller than 1sec? If this is easy, I'd be grateful - otherwise, I can live happily with it the way it is.

Thanks!

**Comment by roblatour** [comment]
While the minimum amount of time that you can specify for the listening period is 1 second, sampling is done every 1/10th of a second.  According, if, for example, music is being played on the device that SetVol will be listening on prior to SetVol being run, it will only take approximately 1/10th of a second for SetVol to recognize that and continue on in its processing.  However, additional time is required to load and unload the application.  All in all about a second.  Not much I can do about the load and unload time.

With thanks to Nusi and their code here:
[](https://stackoverflow.com/questions/605522/print-time-in-a-batch-file-milliseconds)
Here is a batch file you can use to test it:

`@echo off
setlocal

c:
cd "c:\program files\setvol\

rem The format of %TIME% is HH:MM:SS,CS for example 23:59:59,99
set STARTTIME=%TIME%

rem here begins the command you want to measure
setvol listen 5
rem here ends the command you want to measure

set ENDTIME=%TIME%

rem output as time
echo STARTTIME: %STARTTIME%
echo ENDTIME: %ENDTIME%

rem convert STARTTIME and ENDTIME to centiseconds
set /A STARTTIME=(1%STARTTIME:~0,2%-100)*360000 + (1%STARTTIME:~3,2%-100)*6000 + (1%STARTTIME:~6,2%-100)*100 + (1%STARTTIME:~9,2%-100)
set /A ENDTIME=(1%ENDTIME:~0,2%-100)*360000 + (1%ENDTIME:~3,2%-100)*6000 + (1%ENDTIME:~6,2%-100)*100 + (1%ENDTIME:~9,2%-100)

rem calculating the duratyion is easy
set /A DURATION=%ENDTIME%-%STARTTIME%

rem we might have measured the time inbetween days
if %ENDTIME% LSS %STARTTIME% set set /A DURATION=%STARTTIME%-%ENDTIME%

rem now break the centiseconds down to hors, minutes, seconds and the remaining centiseconds
set /A DURATIONH=%DURATION% / 360000
set /A DURATIONM=(%DURATION% - %DURATIONH%*360000) / 6000
set /A DURATIONS=(%DURATION% - %DURATIONH%*360000 - %DURATIONM%*6000) / 100
set /A DURATIONHS=(%DURATION% - %DURATIONH%*360000 - %DURATIONM%*6000 - %DURATIONS%*100)

rem some formatting
if %DURATIONH% LSS 10 set DURATIONH=0%DURATIONH%
if %DURATIONM% LSS 10 set DURATIONM=0%DURATIONM%
if %DURATIONS% LSS 10 set DURATIONS=0%DURATIONS%
if %DURATIONHS% LSS 10 set DURATIONHS=0%DURATIONHS%

rem outputing
echo STARTTIME: %STARTTIME% centiseconds
echo ENDTIME: %ENDTIME% centiseconds
echo DURATION: %DURATION% in centiseconds
echo %DURATIONH%:%DURATIONM%:%DURATIONS%,%DURATIONHS%

pause
`

**Comment by cssyphus** [comment]
Hi Rob, I apologize for not communicating better. If sound is playing, the return is instantaneous - no problem there. It is only when sound is not playing that the minimum wait time is 1sec, and sometimes it needn't be that long - half the time or less would suffice.  But, as I say, the way it is now is pretty close to perfection. Close enough, really. Thanks again and Best of the Season.

**Comment by roblatour** [comment]
I just released setvol 3.1; it now allows you to identify a listening period as a decimal number (of seconds), for example:
setvol listen 0.5
