### ISSUE TITLE
regarding delay in commandline execution

### ISSUE THREAD

**Issue by thrive4** [roblatour/setvol#4]
First off many thanks for sharing your app with us!

I have noticed similar to this posting (Roobles):
https://www.push2run.com/phpbb/viewtopic.php?t=814
that after setting the volume (for example) thru:
setvol +20
or
setvol -20
or
setvol mute
or
setvol unmute

there is a delay after executing the desired state and termination
of setvol.exe

After looking through the code:
https://github.com/roblatour/setvol/blob/main/setvol/Main.vb
@line 747
 ' zero to one hundred
            NewVolume = ConvertFromWords(CommandLine)
            If ((NewVolume >= 0) AndAlso (NewVolume <= 100)) Then
                Dim NewVolSingle As Single = NewVolume / 100
                SetTheLevel(NewVolSingle)
                MasterVolumeLevelChanged = True
                GoTo AllGood
            End If

The code goes to 'AllGood' @816:
AllGood:

        If gDev Is Nothing Then GoTo WrapUp

Then (pending on gdev) it goes to 'WrapUp' @909
where it, as far as I can tell goes through quite a
lot of code... before terminating.

I am by no means sure but is this necessary?
Something similar happens for muting.

Possibly terminating earlier after setvol n
or setvol mute would reduce execution time
allowing setvol.exe to be used some what more
dynamically.

**Comment by thrive4** [comment]
Just a small example possibly for inspiration:
https://docs.microsoft.com/en-us/windows/win32/coreaudio/endpointvolume
Code:
https://github.com/microsoft/Windows-classic-samples/blob/main/Samples/Win7Samples/multimedia/audio/EndpointVolume/endpointvolumechanger.cpp

**Comment by roblatour** [comment]
You may want to relook at the code as posted. 

After going to #wrapup: the program only executes a very small amount of code (less than five lines of code) all necissary.

**Comment by thrive4** [comment]
Thank you for a speedy reply.
Ok... so

@909 Private Function MainLine....
WrapUp:
        If (gCurrentColour <> gStartingColour) Then
            Console_WriteLineInColour(" ", Console.ForegroundColor)
        End If
        Return ReturnCode
    End Function

Initiated from Sub Main() ... ~140
        If gDeviceTable Is Nothing Then
            Console_WriteLineInColour("No sound devices found", ConsoleColor.Red)
        Else
            ReturnCode = MainLine(CommandLine)
        End If
        Console.ForegroundColor = gStartingColour
Environment.Exit(ReturnCode)

I really do not know that much about these specific api's
but possibly something sticks with:
https://docs.microsoft.com/en-us/dotnet/api/system.environment.exit?view=net-6.0

or maybe it's a windows 7 thing anyway ....

All though this is a static image
![setvolexample](https://user-images.githubusercontent.com/58812072/166112086-4cd49ca3-5912-4469-9b84-72f2e7cd6e7d.jpg)

An attempt to illustrate what happens
setvol +10
the mixer responds almost immediately visible (very fast)
setvol then chews on something... for a number
of seconds before terminating (see cursor prompt
in cmd)

Hope this helps if not let's call it a day ;)
and feel free to close the issue.

**Comment by thrive4** [comment]
Just a fyi found an alternative:
https://www.nirsoft.net/utils/sound_volume_command_line.html
regrettably no source code available so setvol can be preferable if needed.
