### ISSUE TITLE
Problem with line 855 in Main.vb

### ISSUE THREAD

**Issue by Galenmacil** [roblatour/setvol#7]
For some reason I do not fully understand, this line don't behave as expected when the following commands are issued to SetVol:

setvol 40 balance 100:0
setvol 40 balance 100:01
setvol 40 balance 100:12
setvol 40 balance 100:23
...
setvol 40 balance 100:78
setvol 40 balance 100:89
setvol 40 balance 100:90

Basically, if the last entered value is made up of two successive digits (12, 23, 34, 45, etc.) or 0 it cause an error.

This does not apply to the following lines as shown below because the successive digit are not at the end of the string:

setvol 40 balance 100:45:0:0:100:100
setvol 40 balance 34:45:56:67:78:98

**Comment by roblatour** [comment]
Thanks, this was corrected this morning; the code is now updated on github and the downloadable executable is available on the website
